#priority 1100

import crafttweaker.item.IItemStack;

var recipe as IItemStack[] = [
	/*4096k-ME存储组件*/<extracells:storage.component:2>,/*16384k-ME存储组件*/<extracells:storage.component:3>,
	//A
		//ai
			/*艾恩尼太阳能板*/<environmentaltech:solar_cell_ionite>,/*艾洛蒂太阳能板*/<environmentaltech:solar_cell_erodium>,
		//an
			/*暗物质台座*/<projecte:dm_pedestal>,
		//ao
			/*奥术石材*/<thaumcraft:stone_arcane>,
	//B
		//ba
			/*八位电容*/<enderio:item_basic_capacitor:2>,
		//bi
			/*铋锭*/<contenttweaker:bismuth_ingot>,/*铋粉*/<contenttweaker:bismuth_dust>,
		//bo
			/*铂齿轮*/<thermalfoundation:material:262>,/*玻璃安瓿*/<thaumcraft:phial>,
	//C
		//cai
			/*彩虹发电机*/<extrautils2:rainbowgenerator>,
		//ce
			/*测试密钥*/<deepmoblearning:trial_key>,/*测试楔石*/<deepmoblearning:trial_keystone>,
		//che
			/*车床*/<advancedrocketry:lathe>,
		//cheng
			/*澄澈结构镶板*/<environmentaltech:structure_panel_clear>,/*成分传感器*/<advancedrocketry:satelliteprimaryfunction:1>,/*成型核心*/<appliedenergistics2:material:43>,
		//chong
			/*充能立方*/<calculator:powercube>,/*充能器*/<appliedenergistics2:charger>,/*充能台*/<actuallyadditions:block_empowerer>,/*重组室*/<calculator:reassemblychamber>,
	//D
		//da
			/*大型太阳能板*/<advancedrocketry:satellitepowersource:1>,
		//dan
			/*单推进火箭发动机*/<advancedrocketry:rocketmotor>,/*单推进燃料箱*/<advancedrocketry:fueltank>,
		//dao
			/*导航电脑*/<advancedrocketry:guidancecomputer>,
		//di
			/*低等共价粉*/<projecte:item.pe_covalence_dust>,
		//dian
			/*电磁线圈*/<mekanismgenerators:generator:9>,/*电动马达*/<nuclearcraft:part:8>,/*电弧高炉*/<advancedrocketry:arcfurnace>,/*点火器*/<roots:fire_starter>,/*电解核心*/<mekanism:electrolyticcore>,/*电解机*/<alchemistry:electrolyzer>,/*电锯*/<advancedrocketry:sawblade>,
		//dong
			/*动能发电机*/<immersiveengineering:metal_device1:2>,
	//E
		//e
			/*恶魔之泪*/<randomthings:ingredient:1>,
		//er
			/*二极管*/<environmentaltech:diode>,/*二级结构方块*/<environmentaltech:structure_frame_2>,/*二阶电池*/<actuallyadditions:item_battery_double>,/*二硼化镁螺线圈*/<nuclearcraft:part:5>,
	//F
		//fa
			/*发电机模块*/<immersiveengineering:metal_decoration0:6>,/*发酵桶*/<actuallyadditions:block_fermenting_barrel>,/*发热元件*/<mekanism:basicblock2:5>,/*发射台*/<advancedrocketry:launchpad>,/*法师护手*/<thaumcraft:caster_basic>,/*发条引擎*/<forestry:engine_clockwork>,
		//fan
			/*反应堆单元*/<nuclearcraft:cell_block>,/*反应堆控制器*/<mekanismgenerators:reactor>,/*反应堆稳定器聚焦环*/<draconicevolution:reactor_part:4>,/*反应堆稳定器框架*/<draconicevolution:reactor_part>,/*反应堆稳定器内转子*/<draconicevolution:reactor_part:1>,/*反应堆稳定器外转子*/<draconicevolution:reactor_part:2>,/*反应堆稳定器转子总成*/<draconicevolution:reactor_part:3>,
		//fang
			/*方镁矾混合物*/<embers:blend_caminite>,
		//fei
			/*飞龙能量核心*/<draconicevolution:wyvern_energy_core>,
		//fen
			/*分析室*/<calculator:analysingchamber>,/*分压元件*/<mekanism:basicblock2:6>,/*分子装配室*/<appliedenergistics2:molecular_assembler>,
		//feng
			/*封包组件*/<packagedauto:package_component>,
		//fu
			/*福鲁伊克斯珍珠*/<appliedenergistics2:material:9>,/*符文祭坛*/<botania:runealtar>,/*复杂旋钮装置*/<mekanismgenerators:generator:8>,/*复制-粘贴小帮手*/<buildinggadgets:copypastetool>,
	//G
		//gai
			/*盖亚水晶*/<botania:pylon:2>,
		//gang
			/*钢 棒*/<libvulpes:productrod:6>,/*钢板*/<immersiveengineering:metal:38>,/*钢齿轮*/<thermalfoundation:material:288>,<libvulpes:productgear:6>,/*钢锭*/<mekanism:ingot:4>,<tcomplement:materials:10>,/*钢质机壳*/<mekanism:basicblock:8>,/*钢制机械零件*/<immersiveengineering:material:9>,
		//gao
			/*高等共价粉*/<projecte:item.pe_covalence_dust:2>,/*高级板*/<nuclearcraft:part:1>,/*高级充能立方*/<calculator:advancedpowercube>,/*高级工作台*/<extendedcrafting:table_advanced>,/*高级合成催化剂*/<extendedcrafting:material:9>,/*高级合成组件*/<extendedcrafting:material:15>,/*高级火箭发动机*/<advancedrocketry:advrocketmotor>,/*高级机器结构方块*/<libvulpes:advstructuremachine>,/*高级卡*/<appliedenergistics2:material:28>,/*高级控制电路*/<mekanism:controlcircuit:1>,/*高级马达*/<libvulpes:advancedmotor>,/*高级双推进火箭发动机*/<advancedrocketry:advbipropellantrocketmotor>,/*高级温室*/<calculator:advancedgreenhouse>,/*高级线圈*/<actuallyadditions:item_misc:8>,/*高级印刷电路板*/<pneumaticcraft:advanced_pcb>,/*高级组件*/<calculator:advancedassembly>,/*高炉控制器*/<tcomplement:high_oven_controller>,/*高炉预热器*/<immersiveengineering:metal_device1>,
		//ge
			/*隔热砖*/<advancedrocketry:blastbrick>,
		//geng
			/*更替小帮手*/<buildinggadgets:exchangertool>,
		//gong
			/*工程师装配台*/<immersiveengineering:wooden_device0:2>,/*共振仪*/<extrautils2:resonator>,/*供桌*/<naturesaura:offering_table>,
		//gu
			/*固体燃料*/<tinker_io:solidfuel>,/*故障灌注护腿*/<deepmoblearning:glitch_infused_leggings>,/*故障灌注剑*/<deepmoblearning:glitch_infused_sword>,/*故障灌注头盔*/<deepmoblearning:glitch_infused_helmet>,/*故障灌注胸甲*/<deepmoblearning:glitch_infused_chestplate>,/*故障灌注靴子*/<deepmoblearning:glitch_infused_boots>,
		//guo
			/*锅炉*/<embers:boiler>,
		//guang
			/*光电电池*/<environmentaltech:photovoltaic_cell>,/*光束炮*/<embers:beam_cannon>,/*光学传感器*/<advancedrocketry:satelliteprimaryfunction>,
	//H
		//hao
			/*好漂亮的方块*/<tinker_io:what_a_beautiful_block>,
		//he
			/*合成核心*/<extendedcrafting:crafting_core>,/*合成计算器*/<calculator:craftingcalculator>,/*合金储罐*/<tcomplement:alloy_tank>,/*合金炉*/<nuclearcraft:alloy_furnace_idle>,/*核热火箭引擎*/<advancedrocketry:nuclearrocketmotor>,/*核热推进火箭燃料箱*/<advancedrocketry:nuclearfueltank>,/*核熔炉*/<nuclearcraft:nuclear_furnace_idle>,
		//hei
			/*黑铁灯*/<extendedcrafting:lamp>,<extendedcrafting:lamp:1>,/*黑铁框架*/<extendedcrafting:frame>,
		//hong
			/*红石传导线圈*/<thermalfoundation:material:515>,/*红石传输线圈*/<thermalfoundation:material:514>,/*红石工程块*/<immersiveengineering:metal_decoration0:3>,/*红石琥珀金齿轮*/<redstonearsenal:material:96>,/*红石琥珀金粉末*/<redstonearsenal:material>,/*红石接收线圈*/<thermalfoundation:material:513>,/*红石伺服器*/<thermalfoundation:material:512>,
		//hu
			/*呼唤之魂*/<naturesaura:calling_spirit>,/*互联方块*/<environmentaltech:interconnect>,/*琥珀金板*/<embers:plate_electrum>,<immersiveengineering:metal:37>,/*琥珀金齿轮*/<thermalfoundation:material:289>,
		//hua
			/*化学反应器*/<advancedrocketry:chemicalreactor>,/*化学化合机*/<alchemistry:chemical_combiner>,/*化学溶解机*/<alchemistry:chemical_dissolver>,/*花药台*/<botania:altar>,
		//huang
			/*黄铜板*/<thaumcraft:plate>,
		//hui
			/*灰烬护身符*/<embers:ashen_amulet>,/*灰烬晶体开采机*/<embers:ember_bore>,/*灰烬炉*/<embers:cinder_plinth>,/*灰烬能量催化器*/<embers:ember_activator>,/*灰烬能量发射器*/<embers:ember_emitter>,/*灰烬能量接收器*/<embers:ember_receiver>,/*灰烬能量喷发器*/<embers:ember_pulser>,
		//hun
			/*混沌碎片*/<draconicevolution:chaos_shard>,
		//huo
			/*钬锭*/<contenttweaker:holmium_ingot>,/*钬粉*/<contenttweaker:holmium_dust>,/*火箭监测站*/<advancedrocketry:monitoringstation>,/*火箭组装机*/<advancedrocketry:rocketbuilder>,
	//J
		//ji
			/*基础板*/<nuclearcraft:part>,/*基础电容*/<enderio:item_basic_capacitor>,/*基础分离器*/<calculator:stoneseparator>,/*基础工作台*/<extendedcrafting:table_basic>,/*基础合成催化剂*/<extendedcrafting:material:8>,/*基础合成组件*/<extendedcrafting:material:14>,/*基础卡*/<appliedenergistics2:material:25>,/*基础太阳能板*/<advancedrocketry:satellitepowersource>,/*基础透镜*/<advancedrocketry:lens>,/*基础温室*/<calculator:basicgreenhouse>,/*基础线圈*/<actuallyadditions:item_misc:7>,/*基础组件*/<calculator:calculatorassembly>,/*激光核心*/<environmentaltech:laser_core>,/*机器结构方块*/<libvulpes:structuremachine>,/*机器框架*/<nuclearcraft:part:10>,<thermalexpansion:frame>,/*机器零件*/<enderio:item_material:2>,/*机巧箱*/<botania:opencrate:1>,/*计算器*/<calculator:calculator>,/*计算器显示屏*/<calculator:calculatorscreen>,/*机械核心*/<embers:mech_core>,/*机械控制器*/<modularmachinery:blockcontroller>,/*基座*/<extendedcrafting:pedestal>,
		//jian
			/*坚固部件*/<forestry:sturdy_machine>,/*简易机器零件*/<enderio:item_material:69>,/*简易机器外壳*/<enderio:item_material>,/*建筑小帮手*/<buildinggadgets:buildingtool>,
		//jiao
			/*搅拌机*/<embers:mixer>,/*焦黑熔炉控制器*/<tconstruct:seared_furnace_controller>,
		//jie
			/*结构塔*/<advancedrocketry:structuretower>,/*结构镶板*/<environmentaltech:structure_panel>,/*结晶器*/<advancedrocketry:crystallizer>,
		//jin
			/*金板*/<embers:plate_gold>,<immersiveengineering:metal:40>,/*金齿轮*/<thermalfoundation:material:25>,/*金推进器*/<simplyjetpacks:metaitemmods:1>,/*金叶粉*/<naturesaura:gold_powder>,
		//jing
			/*晶胞灰烬能量单元*/<embers:crystal_cell>,/*精华板*/<nuclearcraft:part:3>,/*精炼厂*/<pneumaticcraft:refinery>,/*精灵工匠台*/<roots:fey_crafter>,/*精灵门核心*/<botania:alfheimportal>,/*精密激光蚀刻器*/<advancedrocketry:precisionlaseretcher>,/*精密组装机*/<advancedrocketry:precisionassemblingmachine>,/*晶素合成催化剂*/<extendedcrafting:material:12>,/*晶体催生器*/<appliedenergistics2:quartz_growth_accelerator>,/*精英工作台*/<extendedcrafting:table_elite>,/*精英合成催化剂*/<extendedcrafting:material:10>,/*精英合成组件*/<extendedcrafting:material:16>,/*精英控制电路*/<mekanism:controlcircuit:2>,/*精英马达*/<libvulpes:elitemotor>,
		//ju
			/*聚变仓壁*/<alchemistry:fusion_casing>,/*聚变仓核心*/<alchemistry:fusion_core>,/*聚变仓控制器*/<alchemistry:fusion_controller>,/*聚变堆核心*/<nuclearcraft:fusion_core>,/*聚变连接器*/<nuclearcraft:fusion_connector>,/*聚合核心*/<draconicevolution:fusion_crafting_core>,/*聚合粘土*/<deepmoblearning:polymer_clay>,/*聚能石英玻璃*/<appliedenergistics2:quartz_vibrant_glass>,/*咀叶发电机*/<actuallyadditions:block_leaf_generator>,
		//juan
			/*卷板机*/<advancedrocketry:rollingmachine>,
	//K
		//kai
			/*凯罗尼太阳能板*/<environmentaltech:solar_cell_kyronite>,
		//kang
			/*康铜板*/<immersiveengineering:metal:36>,/*康铜齿轮*/<thermalfoundation:material:292>,
		//kong
			/*空白数据模型*/<deepmoblearning:data_model_blank>,/*空白样板*/<appliedenergistics2:material:52>,/*空间站ID芯片*/<advancedrocketry:spacestationchip>,/*空框架*/<nuclearcraft:part:11>,/*空冷却器*/<nuclearcraft:cooler>,/*控制器*/<xnet:controller>,/*控制芯片板*/<advancedrocketry:ic:3>,
		//ku
			/*枯竭铀板*/<nuclearcraft:part:2>,
		//kuang
			/*矿工透镜*/<actuallyadditions:item_mining_lens>,/*矿物粉碎机*/<tinker_io:ore_crusher>,
	//L
		//li
			/*离魂机器框架*/<enderio:item_material:55>,/*沥青质泥炭*/<forestry:bituminous_peat>,/*粒子生成器*/<draconicevolution:particle_generator>,
		//lian
			/*连接器*/<environmentaltech:connector>,/*炼金台*/<embers:alchemy_tablet>,
		//liang
			/*两仓磨粉机*/<actuallyadditions:block_grinder_double>,/*两仓熔炉*/<actuallyadditions:block_furnace_double>,/*量子采石场*/<extrautils2:quarry>,/*量子压缩机*/<extendedcrafting:compressor>,
		//liao
			/*瞭望台*/<advancedrocketry:observatory>,
		//lie
			/*裂变仓控制器*/<alchemistry:fission_controller>,/*裂变反应堆外壳*/<nuclearcraft:fission_block>,/*裂变控制器*/<nuclearcraft:fission_controller_new_fixed>,/*烈焰木*/<tconstruct:firewood:1>,
		//lin
			/*凛冰冷却单元（空）*/<simplyjetpacks:metaitemmods:29>,
		//ling
			/*灵气充能台*/<naturesaura:rf_converter>,
		//liu
			/*六级结构方块*/<environmentaltech:structure_frame_6>,/*流明齿轮*/<thermalfoundation:material:294>,/*流明粉*/<thermalfoundation:material:102>,/*流体适配型样板编码台*/<ae2fc:fluid_pattern_encoder>,
		//long
			/*龙芯*/<draconicevolution:draconic_core>,
		//lun
			/*轮机转子*/<pneumaticcraft:turbine_rotor>,
		//lv
			/*铝板*/<embers:plate_aluminum>,<immersiveengineering:metal:31>,/*绿宝石粒*/<extendedcrafting:material:129>,/*铝齿轮*/<thermalfoundation:material:260>,
	//M
		/*ME安全终端*/<appliedenergistics2:security_station>,/*ME成型面板*/<appliedenergistics2:part:320>,/*ME封包组件*/<packagedauto:me_package_component>,/*ME控制器*/<appliedenergistics2:controller>,/*ME流体成型面板*/<appliedenergistics2:part:321>,/*ME流体封包解码器*/<ae2fc:fluid_packet_decoder>,/*ME流体离散器*/<ae2fc:fluid_discretizer>,/*ME流体破坏面板*/<appliedenergistics2:part:302>,/*ME流体输出总线*/<appliedenergistics2:part:261>,/*ME流体输入总线*/<appliedenergistics2:part:241>,/*ME破坏面板*/<appliedenergistics2:part:300>,/*ME驱动器*/<appliedenergistics2:drive>,/*ME输出总线*/<appliedenergistics2:part:260>,/*ME输入总线*/<appliedenergistics2:part:240>,/*ME箱子*/<appliedenergistics2:chest>,
		//ma
			/*马达*/<libvulpes:motor>,/*麻袋*/<actuallyadditions:item_bag>,
		//mei
			/*煤炭发电机*/<actuallyadditions:block_coal_generator>,
		//mi
			/*密封管*/<advancedrocketry:pipesealer>,
		//mo
			/*魔法水晶*/<botania:pylon>,/*磨粉机*/<actuallyadditions:block_grinder>,/*魔幻雪世界球*/<extrautils2:snowglobe>,/*模块化合金锭*/<modularmachinery:itemmodularium>,/*魔力池*/<botania:pool>,/*魔力发射器*/<botania:spreader>,/*魔力风暴*/<botania:manabomb>,/*魔力石板*/<botania:manatablet>,/*魔力谐振器*/<thaumcraft:vis_resonator>,/*魔力转换器*/<botania:rfgenerator>,/*模拟室*/<deepmoblearning:simulation_chamber>,/*末影齿轮*/<thermalfoundation:material:295>,/*末影发电机*/<extendedcrafting:ender_alternator>,/*末影粉*/<thermalfoundation:material:103>,/*末影钢机器框架*/<enderio:item_material:66>,/*末影工作台*/<extendedcrafting:ender_crafter>,
		//mu
			/*木锄*/<minecraft:wooden_hoe>,/*木墩*/<naturesaura:wood_stand>,/*木斧*/<minecraft:wooden_axe>,/*木镐*/<minecraft:wooden_pickaxe>,/*木工机*/<forestry:carpenter>,/*木棍*/<minecraft:stick>,/*木锹*/<minecraft:wooden_shovel>,/*木质外壳*/<actuallyadditions:block_misc:4>,/*木桌*/<thaumcraft:table_wood>,
	//N
		//neng
			/*能量单元框架*/<thermalexpansion:frame:128>,/*能量阀门*/<draconicevolution:flow_gate>,/*能量核心稳定器*/<draconicevolution:particle_generator:2>,/*能量注入器*/<draconicevolution:energy_infuser>,/*能源接收器*/<appliedenergistics2:energy_acceptor>,/*能源炉*/<thermalexpansion:dynamo:*>,/*能源元件*/<appliedenergistics2:energy_cell>,
		//ni
			/*泥潭引擎*/<forestry:engine_peat>,
		//nie
			/*镍板*/<embers:plate_nickel>,<immersiveengineering:metal:34>,/*镍齿轮*/<thermalfoundation:material:261>,
		//nong
			/*农场*/<actuallyadditions:block_farmer>,
	//P
		/*p2p通道*/<appliedenergistics2:part:460>,
		//pi
			/*皮带*/<simplyjetpacks:metaitem:4>,
		//ping
			/*瓶与塞*/<naturesaura:bottle_two_the_rebottling>,
		//po
			/*破坏核心*/<appliedenergistics2:material:44>,/*破坏小帮手*/<buildinggadgets:destructiontool>,
		//pu
			/*普雷蒂太阳能板*/<environmentaltech:solar_cell_pladium>,
	//Q
		//qi
			/*气体收集器*/<advancedrocketry:intake>,/*气体装填台*/<advancedrocketry:oxygencharger>,
		//qian
			/*铅板*/<embers:plate_lead>,<immersiveengineering:metal:32>,/*铅齿轮*/<thermalfoundation:material:259>,/*铅石推进器*/<simplyjetpacks:metaitemmods:20>,
		//qiang
			/*强化部件核心*/<valkyrielib:modifier_component>,/*强化机器零件*/<enderio:item_material:68>,/*强化机械外壳*/<modularmachinery:blockcasing:4>,/*强化马达*/<libvulpes:enhancedmotor>,/*强化推进器*/<simplyjetpacks:metaitemmods:22>,
		//qie
			/*切割机*/<advancedrocketry:cuttingmachine>,
		//qing
			/*青铜板*/<embers:plate_bronze>,/*青铜齿轮*/<forestry:gear_bronze>,<thermalfoundation:material:291>,/*青铜锭*/<mekanism:ingot:2>,/*轻型工程块*/<immersiveengineering:metal_decoration0:4>,
	//R
		//ran
			/*燃料输入机*/<tinker_io:fuel_input_machine>,/*燃煤发电机*/<libvulpes:coalgenerator>,/*燃烧室外壳*/<modularmachinery:blockcasing:2>,
		//re
			/*热传导发电机*/<immersiveengineering:metal_device1:3>,/*热电子加工机*/<forestry:fabricator>,/*热能发电机*/<actuallyadditions:block_heat_collector>,/*热力蒸馏控制器*/<mekanism:basicblock:14>,/*热气动加工机*/<pneumaticcraft:thermopneumatic_processing_plant>,
		//rong
			/*熔炼炉*/<embers:block_furnace>,/*熔炉*/<minecraft:furnace>,
	//S
		//san
			/*三级结构方块*/<environmentaltech:structure_frame_3>,/*三阶电池*/<actuallyadditions:item_battery_triple>,/*散热器模块*/<immersiveengineering:metal_decoration0:7>,
		//sao
			/*扫描器*/<scannable:scanner>,
		//sen
			/*森流之石*/<roots:grove_stone>,
		//shan
			/*闪耀纤维*/<naturesaura:gold_fiber>,
		//she
			/*设备框架*/<thermalexpansion:frame:64>,
		//shen
			/*深度学习器*/<deepmoblearning:deep_learner>,/*神龙能量核心*/<draconicevolution:draconic_energy_core>,/*神秘板*/<thaumcraft:plate:2>,
		//sheng
			/*生存者发电机*/<extrautils2:machine>.withTag({Type: "extrautils2:generator_survival"}),/*升级：通量维修复原*/<thermalexpansion:augment:401>,
		//shi
			/*时间洪流怀表*/<projecte:item.pe_time_watch>,/*时间之瓶*/<randomthings:timeinabottle>,/*世界盐*/<thaumcraft:salis_mundus>,/*石桶*/<tcomplement:materials>,/*石英坩埚*/<advancedrocketry:iquartzcrucible>,/*石英磨具*/<appliedenergistics2:grindstone>,
		//shou
			/*手持工作台*/<actuallyadditions:item_crafter_on_a_stick>,<extendedcrafting:handheld_table>,/*手摇发电机*/<calculator:handcrankedgenerator>,
		//shu
			/*数字化苦难之井*/<deepmoblearningbm:digital_agonizer>,
		//shuai
			/*衰变产能器*/<nuclearcraft:decay_generator>,
		//shuang
			/*双层电容*/<enderio:item_basic_capacitor:1>,/*双锂 水晶*/<libvulpes:productgem>,/*双推进火箭发动机*/<advancedrocketry:bipropellantrocketmotor>,/*双推进燃料箱*/<advancedrocketry:bipropellantfueltank>,/*双足飞龙核心*/<draconicevolution:wyvern_core>,
		//shui
			/*水晶黏合剂*/<nuclearcraft:compound:1>,/*水泥*/<tconstruct:soil>,
		//si
			/*伺服系统*/<nuclearcraft:part:7>,/*四级结构方块*/<environmentaltech:structure_frame_4>,/*四阶电池*/<actuallyadditions:item_battery_quadruple>,/*斯特林引擎*/<tinker_io:stirling_engine>,
		//su
			/*塑料混合机*/<pneumaticcraft:plastic_mixer>,
	//T
		//tai
			/*钛 棒*/<libvulpes:productrod:7>,/*钛 齿轮*/<libvulpes:productgear:7>,/*太空站组装机*/<advancedrocketry:stationbuilder>,/*泰拉凝聚板*/<botania:terraplate>,/*钛铝合金 棒*/<advancedrocketry:productrod>,/*钛铝合金 齿轮*/<advancedrocketry:productgear>,/*钛铱合金 棒*/<advancedrocketry:productrod:1>,/*钛铱合金 齿轮*/<advancedrocketry:productgear:1>,
		//tan
			/*炭灰板材*/<deepmoblearning:soot_covered_plate>,/*炭灰板材机械外壳*/<deepmoblearning:machine_casing>,/*坦桑石块*/<biomesoplenty:gem_block:4>,
		//tao
			/*陶瓷合金储罐*/<tcomplement:porcelain_alloy_tank>,/*陶瓷加热器*/<tcomplement:porcelain_melter:8>,
		//ti
			/*提取室*/<calculator:extractionchamber>,
		//tian
			/*天体数据处理器*/<advancedrocketry:planetanalyser>,
		//tie
			/*铁 棒*/<libvulpes:productrod:1>,/*铁板*/<embers:plate_iron>,<immersiveengineering:metal:39>,<thaumcraft:plate:1>,/*铁齿轮*/<thermalfoundation:material:24>,/*铁护甲板*/<simplyjetpacks:metaitemmods:16>,/*铁锯片*/<advancedrocketry:sawbladeiron>,/*铁推进器*/<simplyjetpacks:metaitemmods>,/*铁质机械零件*/<immersiveengineering:material:8>,/*铁制外壳*/<actuallyadditions:block_misc:9>,
		//ting
			/*停靠台*/<advancedrocketry:landingpad>,
		//tong
			/*铜 棒*/<libvulpes:productrod:4>,/*铜板*/<embers:plate_copper>,<immersiveengineering:metal:30>,/*铜齿轮*/<forestry:gear_copper>,<thermalfoundation:material:256>,/*铜锭*/<mekanism:ingot:5>,/*通量核心*/<fluxnetworks:fluxcore>,/*铜螺线管*/<nuclearcraft:part:4>,/*铜质灰烬能量单元*/<embers:copper_cell>.withTag({emberCapacity: 24000.0, ember: 0.0}),
	//W
		//wai
			/*外置加热器*/<immersiveengineering:metal_device1:1>,
		//wan
			/*完美温室*/<calculator:flawlessgreenhouse>,
		//wei
			/*微缩陶瓷冶炼炉*/<tcomplement:porcelain_melter>,/*卫星*/<advancedrocketry:satellite>,/*卫星仓*/<advancedrocketry:loader:1>,/*卫星ID芯片*/<advancedrocketry:satelliteidchip>,/*卫星建造机*/<advancedrocketry:satellitebuilder>,/*卫星终端*/<advancedrocketry:satellitecontrolcenter>,
		//wo
			/*涡轮转子*/<mekanismgenerators:generator:7>,
		//wu
			/*钨锭*/<contenttweaker:tungsten_ingot>,/*雾化器*/<alchemistry:atomizer>,/*五级结构方块*/<environmentaltech:structure_frame_5>,/*五阶电池*/<actuallyadditions:item_battery_quintuple>,/*物品IO芯片板*/<advancedrocketry:ic:4>,/*物品收集器*/<actuallyadditions:block_ranged_collector>,/*污染物导管*/<embers:pipe>,/*无人飞船组装器*/<advancedrocketry:deployablerocketbuilder>,/*无瑕组件*/<calculator:flawlessassembly>,/*无线接收器*/<appliedenergistics2:material:41>,/*无线收发器*/<advancedrocketry:wirelesstransciever>,/*无线信号增幅器*/<appliedenergistics2:material:42>,/*无限增幅卡*/<ae2wtlib:infinity_booster_card>,/*无效果强化部件*/<environmentaltech:modifier_null>,/*物质聚合器*/<appliedenergistics2:condenser>,
	//X
		//xi
			/*锡板*/<embers:plate_tin>,/*锡齿轮*/<forestry:gear_tin>,<thermalfoundation:material:257>,/*锡锭*/<mekanism:ingot:6>,/*牺牲匕首*/<bloodmagic:sacrificial_dagger>,/*稀释魔力池*/<botania:pool:2>,
		//xian
			/*线性执行器*/<nuclearcraft:part:9>,
		//xiao
			/*小号电池*/<libvulpes:battery>,/*小行星ID芯片*/<advancedrocketry:asteroidchip>,/*小型压板器*/<advancedrocketry:platepress>,/*小制造机*/<nuclearcraft:manufactory_idle>,
		//xie
			/*谐振推进器*/<simplyjetpacks:metaitemmods:23>,
		//xin
			/*信素齿轮*/<thermalfoundation:material:293>,/*信素粉*/<thermalfoundation:material:101>,
		//xing
			/*星辉合成台*/<astralsorcery:blockaltar>,/*星球ID芯片*/<advancedrocketry:planetidchip>,
		//xiu
			/*修复护符*/<projecte:item.pe_repair_talisman>,/*修复室*/<calculator:restorationchamber>,
		//xu
			/*虚空金属板*/<thaumcraft:plate:3>,
		//xue
			/*血之祭坛*/<bloodmagic:altar>,
	//Y
		//ya
			/*压力室接口*/<pneumaticcraft:pressure_chamber_interface>,/*压力室墙壁*/<pneumaticcraft:pressure_chamber_wall>,/*压缩空间机械制作器*/<compactmachines3:fieldprojector>,/*压缩铁齿轮*/<pneumaticcraft:compressed_iron_gear>,/*压印锤*/<embers:stamper>,/*压印基座*/<embers:stamper_base>,/*压印器*/<appliedenergistics2:inscriber>,
		//yan
			/*研钵*/<roots:mortar>,
		//ye
			/*液化器*/<alchemistry:liquifier>,/*冶金灌注机*/<mekanism:machineblock:8>,/*液冷器*/<nuclearcraft:active_cooler>,/*冶炼炉控制器*/<tconstruct:smeltery_controller>,/*液体IO芯片板*/<advancedrocketry:ic:5>,
		//yi
			/*铱 棒*/<libvulpes:productrod:10>,/*铱齿轮*/<thermalfoundation:material:263>,/*铱粉*/<thermalfoundation:material:71>,/*一级结构方块*/<environmentaltech:structure_frame_1>,/*一阶电池*/<actuallyadditions:item_battery>,/*以太太阳能板*/<environmentaltech:solar_cell_aethium>,
		//yin
			/*银板*/<embers:plate_silver>,<immersiveengineering:metal:33>,/*银齿轮*/<thermalfoundation:material:258>,/*殷钢齿轮*/<thermalfoundation:material:290>,
		//ying
			/*硬化升级套件*/<thermalfoundation:upgrade>,/*硬化推进器*/<simplyjetpacks:metaitemmods:21>,/*硬化铱玻璃*/<thermalfoundation:glass:7>,/*硬化蕴魔秘银玻璃*/<thermalfoundation:glass:8>,/*硬皮*/<harvestcraft:hardenedleatheritem>,
		//yong
			/*用户界面*/<advancedrocketry:misc>,
		//you
			/*油菜压榨机*/<actuallyadditions:block_canola_press>,
		//yu
			/*狱火熔炉*/<bloodmagic:soul_forge>,
		//yuan
			/*原材料缓存仓*/<ae2fc:ingredient_buffer>,/*原始投网*/<bloodmagic:soul_snare>,/*原油发电机*/<actuallyadditions:block_oil_generator>,/*源质离心机*/<advancedrocketry:centrifuge>,/*原子计算器*/<calculator:atomiccalculator>,/*原子模块*/<calculator:atomicmodule>,/*原子粘合剂*/<calculator:atomicbinder>,/*原子再构机*/<actuallyadditions:block_atomic_reconstructor>,/*原子组件*/<calculator:atomicassembly>,
		//yue
			/*跃迁核心*/<advancedrocketry:warpcore>,/*跃迁控制器*/<advancedrocketry:warpmonitor>,/*月蚀计*/<randomthings:eclipsedclock>,
		//yun
			/*蕴魔秘银齿轮*/<thermalfoundation:material:264>,/*运算分离器*/<calculator:algorithmseparator>,/*运算器核心*/<calculator:calculatorlocator>,
	//Z
		//zhan
			/*战利品制造器*/<deepmoblearning:extraction_chamber>,
		//zhao
			/*照明面板*/<appliedenergistics2:part:180>,/*沼气引擎*/<forestry:engine_biogas>,
		//zhen
			/*真空室高能激光发射器*/<advancedrocketry:vacuumlaser>,
		//zheng
			/*蒸发锅*/<alchemistry:evaporator>,
		//zhi
			/*质量检测器*/<advancedrocketry:satelliteprimaryfunction:2>,/*智能输出端*/<tinker_io:smart_output>,
		//zhong
			/*中等共价粉*/<projecte:item.pe_covalence_dust:1>,/*终极催化剂*/<extendedcrafting:material:13>,/*终极工作台*/<extendedcrafting:table_ultimate>,/*终极合成催化剂*/<extendedcrafting:material:11>,/*终极合成组件*/<extendedcrafting:material:17>,/*终极控制电路*/<mekanism:controlcircuit:3>,/*重型工程块*/<immersiveengineering:metal_decoration0:5>,
		//zhu
			/*助燃燃油箱*/<advancedrocketry:oxidizerfueltank>,/*注入龙力的黑曜石*/<draconicevolution:infused_obsidian>,/*铸造盆升级*/<tinker_io:upg:7>,
		//zhuan
			/*转化桌*/<projecte:transmutation_table>,/*转换升级*/<storagedrawers:upgrade_conversion>,
		//zi
			/*自然水晶*/<botania:pylon:1>,/*紫水晶块*/<biomesoplenty:gem_block>,/*紫外光灯箱*/<pneumaticcraft:uv_light_box>,
		//zuan
			/*钻石齿轮*/<thermalfoundation:material:26>,/*钻石粒*/<extendedcrafting:material:128>,<translocators:diamond_nugget>,/*钻石推进器*/<simplyjetpacks:metaitemmods:2>,/*钻头*/<advancedrocketry:drill>,
		//zuo
			/*座位*/<advancedrocketry:seat>
];
var rName as string[] = [
	//C
		//chuan
			/*传送带*/"immersiveengineering:conveyors/conveyor_basic",
		//ci
			/*磁引卡*/"wct:magnet_card",
	//D
		//da
			/*大型混沌残片*/"draconicevolution:chaos_shard_3",
		//dao
			/*导电铁喷气背包*/"simplyjetpacks:upgraderecipeshaped0",
		//di
			/*第三只眼*/"botania:thirdeye",/*低压喷气背包*/"simplyjetpacks:upgraderecipeshaped39",
		//dian
			/*电磁体*/"nuclearcraft:tile.nuclearcraft.fusion_electromagnet_idle",
	//F
		//fang
			/*防腐木板*/"immersiveengineering:treated_wood/treated_wood",
		//fu
			/*附魔器*/"extrautils2:machine_enchanter",
	//G
		//gang
			/*钢块*/"mekanism:basicblock_5","tcomplement:steelworks/steel_block",/*钢粒*/"mekanism:nugget_4","tcomplement:steelworks/steel_nugget",
		//gao
			/*高炉砖*/"immersiveengineering:stone_decoration/blastbrick",
		//gu
			/*骨粉*/"minecraft:bone_meal_from_block","minecraft:bone_meal_from_bone",
	//H
		//he
			/*合成单元*/"appliedenergistics2:network/crafting/cpu_crafting_unit",
		//hei
			/*黑铁锭*/"extendedcrafting:black_iron_ingot",
		//hong
			/*红石水晶*/"redstonearsenal:gem_crystal_flux",
	//J
		//ji
			/*基础喷气背包*/"simplyjetpacks:upgraderecipeshaped35",/*基础注入合成装置*/"draconicevolution:crafting_injector",/*机器方块*/"extrautils2:machine_base",
		//jiao
			/*焦炉砖*/"immersiveengineering:stone_decoration/cokebrick",
	//L
		//lai
			/*莱泽尔水晶*/"environmentaltech:m_resources/litherite/litherite_crystal",
		//li
			/*锂锭*/"thermalfoundation:ingot_9","thermalfoundation:ingot_10","thermalfoundation:ingot_11",
		//liu
			/*流明精华*/"extendedcrafting:luminessence",/*流体精炼机*/"thermalexpansion:machine_7",
		//long
			/*龙锭*/"thermalfoundation:draconium_ingot","thermalfoundation:draconium_ingot_1","thermalfoundation:draconium_ingot_2",
	//M
		/*ME接口*/"appliedenergistics2:network/blocks/interfaces_interface",/*ME流体接口*/"appliedenergistics2:network/blocks/fluid_interfaces_interface",/*ME气体输出总线*/"extracells:parts/gasexportbus",/*ME气体输入总线*/"extracells:parts/gasimportbus",
		//mo
			/*末影锭*/"extendedcrafting:ender_ingot",
		//mu
			/*木炭块*/"actuallyadditions:recipes121","chisel:charcoal","mekanism:basicblock_3","tcomplement:steelworks/charcoal_block",
	//P
		//ping
			/*平板电脑*/"pneumaticcraft:amadron_tablet",
	//Q
		//qing
			/*青铜块*/"mekanism:basicblock_1",/*青铜粒*/"mekanism:nugget_2",
	//T
		//tai
			/*钛 锭*/"thermalfoundation:productingot","thermalfoundation:productingot_1","thermalfoundation:productingot_2",
		//tang
			/*糖*/"minecraft:sugar",
		//tie
			/*铁喷气背包*/"simplyjetpacks:upgraderecipeshaped32",
		//tong
			/*桶*/"minecraft:bucket",/*铜块*/"mekanism:basicblock_12",/*铜粒*/"mekanism:nugget_5",
		//tou
			/*透明聚变电磁体*/"nuclearcraft:tile.nuclearcraft.fusion_electromagnet_transparent_idle",/*透明裂变反应堆外壳*/"nuclearcraft:tile.nuclearcraft.reactor_casing_transparent",
	//X
		//xi
			/*锡块*/"mekanism:basicblock_13",/*锡粒*/"mekanism:nugget_6",
		//xian
			/*贤者之石*/"projecte:philosophers_stone","projecte:philosophers_stone_alt",
	//Y
		//ya
			/*压力室玻璃*/"pneumaticcraft:pressure_chamber_glass",/*压力室气阀*/"pneumaticcraft:pressure_chamber_valve",
		//yao
			/*窑砖*/"immersiveengineering:stone_decoration/alloybrick",
		//yi
			/*铱锭*/"thermalfoundation:material_135","thermalfoundation:material_136","thermalfoundation:material_137",
		//you
			/*铀板*/"immersiveengineering:material/plate_uranium"
];
for array in recipe {recipes.remove(array);}
for array in rName {recipes.removeByRecipeName(array);}
